### PR TITLE
Fix compiling and macOS CMake

### LINKED ISSUE #10: Compilation error on MacOS
Hi 🙋‍♀️ 

Running `cmake .` in the freshly copied repo works fine. Compiling however does not:
Executing `make` results in this 
```
[ 33%] Building C object CMakeFiles/TicTacToe.dir/main.c.o
/Users/teufelchen/Programming/TicTacToe/main.c:20:10: fatal error: 'SDL2/SDL.h' file not found
#include <SDL2/SDL.h>
         ^~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/TicTacToe.dir/main.c.o] Error 1
make[1]: *** [CMakeFiles/TicTacToe.dir/all] Error 2
make: *** [all] Error 2
```

A work around is to run gcc manually:
`gcc main.c include/graphics.c -I/usr/local/include -L/usr/local/lib -lSDL2 -lSDL2_TTF `

However upon executing the program:
```
Welcome to Tic Tac Toe! Copyright (C) 2021
Couldn't load small font! Reason: Couldn't open ../resources/Serif.ttf
Couldn't load small font! Reason: Couldn't open ../resources/Serif.ttf
[1]    74802 segmentation fault  ./a.out
```

Which clearly sucks. 

So we got multiple issues here:

1. The readme does not tell you how to compile and run the program(it should also listen the dependency)
2. `*.ttf` not included in the repo
3. Missing error handling when the Fonts could not be loaded
4. Wrong error message

I would kindly ask you to confirm these issues(it might still be user-error on my side!) and then open separate Github issues for them. 

Thanks in advance!

### PR DESCRIPTION
**Pull request by kosmas12**
Fixes multiple definitions of variables. Also closes #10

### CODE REVIEW

File: include/common.h [hunk 1]
```diff
@@ -5,8 +5,14 @@
...
-int playerScore;
-int aiScore;
-int draws;
+#ifdef MAIN_INCLUDE
+#define EXTERN
+#else
+#define EXTERN extern
+#endif
+
+EXTERN int playerScore;
```
Comment (Teufelchen1) [inline include/common.h:14]: Why in capitals?

File: CMakeLists.txt [hunk 2]
```diff
@@ -8,10 +8,26 @@ set(SOURCE_FILES ${SOURCE_FILES} include/graphics.c)
...
 
+if(${CMAKE_HOST_APPLE})
+    set(SDL2_TTF_INCLUDE_DIRS "/usr/local/Cellar/sdl2_ttf/2.0.15/include/SDL2")
+    set(SDL2_TTF_LIBRARIES "-L/usr/local/Cellar/sdl2_ttf/2.0.15/lib" "-lSDL2_TTF")
+else()
 INCLUDE(FindPkgConfig)
 
 pkg_check_modules(SDL2 REQUIRED sdl2)
 pkg_check_modules(SDL2_TTF REQUIRED SDL2_ttf)
+endif()
```
Comment (Teufelchen1) [inline CMakeLists.txt:19]: SDL2 it self was working as expected, only TTF was having heavy issues. I will test this after finishing the review.
